### PR TITLE
Create DGP-3.md

### PR DESCRIPTION
**Pull request by devender-yadav**

### CODE REVIEW

**Comment by devender-yadav** [comment]
I also see an endpoint https://ipfs.dock.io/api/v0/cat/QmRAJJWA1wk6fDChf2ViZun3WV5yN71ybs1ogf3rg6dtyk

Response:

>{"title":"DGP-1: The Dock Governance Proposal Process","description":"This process is meant to be the first of several steps towards embracing decentralized governance for the betterment of the Dock network and community. We expect DGPs to be a driving force for community input on development decisions that are shaping the future of the Dock network.  \n\nRead the full proposal: https://github.com/getdock/voting/blob/master/DGPs/DGP-1.md","options":["Approve","Reject"]}

If this endpoint is updated with every vote, we can have additional data like docks_voted, days_left, approve_percdent, reject_percent, etc. and this endpoint can do the work needed on DGP-3.

**Comment by devender-yadav** [comment]
@nickmacario what do you think about this?

**Comment by srpattison** [comment]
Hi @devender-yadav, I think this is a great idea. I've been speaking with the devs about a possible overhaul to our approach on the voting page - which would be a good opportunity to add functionality like this. Give me a little time to get some feedback from the devs and put our own proposal together for the larger voting app overhaul. We can push both proposals at the same time.

**Comment by cykoder** [comment]
Hey @devender-yadav - we have implemented a route to pull JSON data - this is updated hourly currently, but that may change as we open new proposals.

https://dock.io/proposals.json

Simply GET this route and parse the data as JSON. Let me know if you need anything else or some help.

**Comment by devender-yadav** [comment]
@SamHellawell looks good. What's the significance of `highestStakeIndex` field?

**Comment by cykoder** [comment]
`highestStakeIndex` returns the index of the winning option

**Comment by devender-yadav** [comment]
@SamHellawell okay. Thanks!

**Comment by srpattison** [comment]
Hi again @devender-yadav - because of the recent changes between Dock and Verifiable, including completely reworking the way we display proposals on the new open-sourced Dock Website (/getdock/website), we were able to make your suggested changes with minimal additional effort.  

For that reason it doesn't make sense to put this to a vote. If you have any other ideas for improvement, because the website is now open source, you can create issues or PRs directly on the website repo now as well!

**Pull request closed without merging**
